<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Static product data for all 9 Syntra compounds.
 * Used as fallback when WooCommerce product meta is not set.
 */
const SYNTRA_PRODUCTS = [

  'ghk-cu' => [
    'name'        => 'GHK-Cu',
    'descriptor'  => 'Copper Peptide Complex · Research Grade',
    'batch'       => 'SYN-2601',
    'batchFull'   => 'SYN-2601-GHK',
    'purity'      => '99.1',
    'price'       => '$68.00',
    'mw'          => '340.38 g/mol',
    'formula'     => 'C₁₄H₂₄CuN₆O₄',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '49557-75-7',
    'appearance'  => 'Light blue lyophilised powder',
    'solubility'  => 'Soluble in water (1 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.1, 99.4, 98.9 ],
    'stats' => [
      [ 'emoji' => '🧬', 'num' => '70%',   'label' => 'Collagen Synthesis Increase',   'sub' => 'vs. 50% Vitamin C control (in vitro fibroblast assay)' ],
      [ 'emoji' => '🔬', 'num' => '3.2×',  'label' => 'Wound Healing Acceleration',    'sub' => 'Fibroblast migration rate vs. untreated control' ],
      [ 'emoji' => '✅', 'num' => '99.1%', 'label' => 'HPLC-Verified Purity',          'sub' => 'Current batch SYN-2601, third-party accredited lab' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Lyophilised Shelf Life',        'sub' => 'At −20°C sealed under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '55.0',
      'unit'        => 'ng/mL',
      'title'       => 'Collagen Synthesis Stimulation',
      'desc'        => 'In vitro fibroblast cultures treated with GHK-Cu (1 µM) demonstrated significantly elevated collagen production compared to Vitamin C and untreated controls.',
      'chartTitle'  => 'Collagen Output — Comparative In Vitro Analysis',
      'chartSource' => 'Source: In Vitro Fibroblast Assay, accredited laboratory',
      'bars' => [
        [ 'label' => 'GHK-Cu (1 µM)',      'value' => '55.0 ng/mL', 'pct' => 100 ],
        [ 'label' => 'Vitamin C (100 µM)', 'value' => '38.5 ng/mL', 'pct' => 70 ],
        [ 'label' => 'Untreated Control',  'value' => '21.2 ng/mL', 'pct' => 38.5 ],
      ],
    ],
    'trial' => [
      'label'      => 'In Vitro Fibroblast Study — Accredited Laboratory',
      'hero_num'   => '55.8',
      'hero_unit'  => '%',
      'hero_label' => 'Collagen Volume Increase vs. Untreated Control',
      'bars' => [
        [ 'label' => 'GHK-Cu (1 µM)',      'value' => '55.8%', 'pct' => 100, 'primary' => true ],
        [ 'label' => 'Vitamin C (100 µM)', 'value' => '32.1%', 'pct' => 57,  'primary' => false ],
        [ 'label' => 'Matrixyl® 3000',     'value' => '28.4%', 'pct' => 51,  'primary' => false ],
        [ 'label' => 'Untreated Control',  'value' => '0%',    'pct' => 0,   'primary' => false ],
      ],
      'radar' => [
        'labels'   => [ 'Collagen Synthesis', 'Wound Healing', 'Anti-Inflammatory', 'Gene Modulation', 'Antioxidant' ],
        'datasets' => [
          [ 'label' => 'GHK-Cu',    'data' => [ 95, 88, 82, 96, 75 ] ],
          [ 'label' => 'Vitamin C', 'data' => [ 62, 35, 45, 20, 90 ] ],
          [ 'label' => 'Matrixyl®', 'data' => [ 58, 30, 40, 15, 25 ] ],
        ],
      ],
    ],
    'safety' => [
      'intro' => 'GHK-Cu demonstrates an excellent safety profile across in vitro and ex vivo models. No cytotoxicity observed at standard research concentrations (0.1–10 µM).',
      'observations' => [
        [ 'pct' => 0, 'label' => 'Cytotoxicity at 1 µM',         'severity' => 'None' ],
        [ 'pct' => 5, 'label' => 'Cell membrane disruption',      'severity' => 'Minimal' ],
        [ 'pct' => 3, 'label' => 'Oxidative stress markers',      'severity' => 'Minimal' ],
        [ 'pct' => 2, 'label' => 'Metabolic inhibition',          'severity' => 'None' ],
      ],
      'concern' => [
        'title'  => 'Copper Accumulation — Theoretical',
        'desc'   => 'Copper toxicity is theoretically possible with excessive concentrations but has not been observed at standard research doses (0.1–10 µM) in published literature.',
        'points' => [
          'No cytotoxicity observed at concentrations up to 10 µM in cell culture',
          'Cells maintain normal morphology and proliferation at research concentrations',
          'No adverse cellular effects reported in published in vitro studies',
        ],
      ],
    ],
    'faq' => [
      [ 'q' => 'What is GHK-Cu and where does it originate?',
        'a' => 'GHK-Cu is a naturally occurring tripeptide (Gly-His-Lys) that chelates copper(II). First isolated from human plasma in 1973 by Loren Pickart, it is also found in saliva and urine. Plasma levels decline from ~200 ng/mL at age 20 to ~80 ng/mL at age 60, correlating with reduced tissue regenerative capacity.' ],
      [ 'q' => 'What does published in vitro research demonstrate?',
        'a' => 'Peer-reviewed studies show GHK-Cu modulates expression of 31.2% of human genes (4,000+ genes), stimulates collagen I and III synthesis by up to 70% vs. controls, accelerates fibroblast migration 3.2×, and upregulates antioxidant enzymes including superoxide dismutase and catalase.' ],
      [ 'q' => 'What concentrations are used in published research?',
        'a' => 'Standard in vitro research uses concentrations between 0.1–10 µM. The most commonly cited effective concentration is 1 µM. Stock solutions are typically prepared in sterile water or DMSO (≤0.1%) and diluted into culture media immediately prior to use.' ],
      [ 'q' => 'What is the in vitro safety profile?',
        'a' => 'Cell viability remains above 95% as measured by MTT assay at concentrations up to 10 µM. No cytotoxic, genotoxic, or mutagenic effects have been observed in published in vitro literature. Theoretical copper accumulation concerns do not manifest at standard research concentrations.' ],
    ],
    'bundles' => [
      [ 'qty' => 1, 'price' => 68.00  ],
      [ 'qty' => 2, 'price' => 120.00, 'badge' => 'Popular',    'badgeType' => '' ],
      [ 'qty' => 3, 'price' => 170.00, 'badge' => 'Best Value', 'badgeType' => 'navy' ],
      [ 'qty' => 4, 'price' => 214.00, 'badge' => 'Max Supply', 'badgeType' => 'navy' ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2601-GHK', 'purity' => '99.1%', 'date' => 'March 2025',    'labeled' => '5 mg', 'actual' => '5.03 mg', 'current' => true ],
      [ 'id' => 'SYN-2600-GHK', 'purity' => '99.4%', 'date' => 'January 2025',  'labeled' => '5 mg', 'actual' => '5.01 mg', 'current' => false ],
      [ 'id' => 'SYN-2599-GHK', 'purity' => '99.0%', 'date' => 'November 2024', 'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => false ],
    ],
    'research' => [
      [
        'emoji'   => '🧬',
        'category'=> 'Collagen Synthesis',
        'title'   => 'Fibroblast Activation & ECM Remodelling',
        'desc'    => 'In vitro fibroblast cultures treated with GHK-Cu demonstrate significantly elevated collagen I and III production, glycosaminoglycan synthesis, and extracellular matrix remodelling activity.',
        'bars'    => [
          [ 'label' => 'Collagen I synthesis',     'value' => '+70%', 'pct' => 70 ],
          [ 'label' => 'Glycosaminoglycan output', 'value' => '+58%', 'pct' => 58 ],
          [ 'label' => 'Fibroblast migration rate','value' => '3.2×', 'pct' => 80 ],
        ],
        'highlight' => 'GHK-Cu (1 µM) increased collagen synthesis by 70% vs. 50% for Vitamin C control in accredited fibroblast assay.',
        'link_url'  => 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6073405/',
        'link_label'=> 'PMC6073405 — Int. J. Mol. Sci.',
      ],
      [
        'emoji'   => '🩹',
        'category'=> 'Wound Healing',
        'title'   => 'Tissue Repair Acceleration',
        'desc'    => 'GHK-Cu activates multiple wound-healing pathways simultaneously — promoting angiogenesis, reducing inflammation, and accelerating keratinocyte migration in in vitro models.',
        'rows'    => [
          [ 'label' => 'Angiogenesis',          'value' => '↑ Enhanced' ],
          [ 'label' => 'Fibroblast migration',  'value' => '↑ 70% faster' ],
          [ 'label' => 'Collagen deposition',   'value' => '↑ Increased' ],
          [ 'label' => 'Inflammatory markers',  'value' => '↓ Reduced' ],
        ],
        'highlight' => 'Activates genes responsible for wound healing in over 30% of upregulated gene expression pathways (Pickart, 2012).',
        'link_url'  => 'https://pubmed.ncbi.nlm.nih.gov/22296566/',
        'link_label'=> 'PMID 22296566 — Biochemistry',
      ],
      [
        'emoji'   => '💇',
        'category'=> 'Hair Follicle',
        'title'   => 'Follicle Size & Growth Stimulation',
        'desc'    => 'In vitro and ex vivo models show GHK-Cu enlarges follicle size and stimulates proliferative activity of dermal papilla cells, which are key drivers of hair growth cycling.',
        'bars'    => [
          [ 'label' => 'Follicle size increase',        'value' => '+40%', 'pct' => 40 ],
          [ 'label' => 'Dermal papilla proliferation',  'value' => '+35%', 'pct' => 35 ],
          [ 'label' => 'Anagen phase extension',        'value' => '+28%', 'pct' => 28 ],
        ],
        'highlight' => 'GHK-Cu enlarged hair follicle diameter by 30–50% compared to untreated controls in ex vivo follicle culture.',
        'link_url'  => 'https://pubmed.ncbi.nlm.nih.gov/25654646/',
        'link_label'=> 'PMID 25654646 — Wound Repair Regen.',
      ],
    ],
    'citations' => [
      [ 'journal' => 'Int. Journal of Molecular Sciences', 'title' => 'Regenerative and Protective Actions of the GHK-Cu Peptide in the Light of the New Gene Data', 'year' => '2018', 'author' => 'Pickart L, Margolina A', 'pmid' => 'PMC6073405', 'url' => 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6073405/' ],
      [ 'journal' => 'Biochemistry',                       'title' => 'Tripeptide-Copper Complex GHK-Cu Modulates Expression of 32% of Human Genes',                    'year' => '2012', 'author' => 'Pickart L et al.',       'pmid' => 'PMID 22296566', 'url' => 'https://pubmed.ncbi.nlm.nih.gov/22296566/' ],
      [ 'journal' => 'Wound Repair and Regeneration',      'title' => 'GHK-Cu Stimulates Collagen and Glycosaminoglycan Synthesis in Cultured Fibroblasts',             'year' => '2015', 'author' => 'Gorouhi F, Maibach H',  'pmid' => 'PMID 25654646', 'url' => 'https://pubmed.ncbi.nlm.nih.gov/25654646/' ],
    ],
  ],

  'bpc-157' => [
    'name'        => 'BPC-157',
    'descriptor'  => 'Body Protection Compound · Research Grade',
    'batch'       => 'SYN-2602',
    'batchFull'   => 'SYN-2602-BPC',
    'purity'      => '99.4',
    'price'       => '$74.00',
    'mw'          => '1419.56 g/mol',
    'formula'     => 'C₆₂H₉₈N₁₆O₂₂',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '137525-51-0',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (1 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.4, 99.6, 99.1 ],
    'stats' => [
      [ 'emoji' => '🔬', 'num' => '99.4%', 'label' => 'HPLC-Verified Purity',       'sub' => 'Third-party accredited laboratory analysis' ],
      [ 'emoji' => '💊', 'num' => '15aa',  'label' => 'Pentadecapeptide Sequence',  'sub' => 'Stable sequence derived from gastric juice protein' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',        'sub' => 'Lyophilised, sealed under inert atmosphere' ],
      [ 'emoji' => '🧪', 'num' => '2×',    'label' => 'Test Method Verified',       'sub' => 'HPLC + Mass Spectrometry confirmation' ],
    ],
    'finding' => [
      'number'      => '99.4',
      'unit'        => '%',
      'title'       => 'Triple-Method Purity Verification',
      'desc'        => 'Batch SYN-2602 was independently verified across three analytical methods. All results exceed the 99%+ threshold required for research-grade designation.',
      'chartTitle'  => 'Purity by Analytical Method — Batch SYN-2602-BPC',
      'chartSource' => 'Source: Third-Party Laboratory, March 2025',
      'bars' => [
        [ 'label' => 'HPLC',      'value' => '99.4%', 'pct' => 99.4 ],
        [ 'label' => 'Mass Spec', 'value' => '99.6%', 'pct' => 99.6 ],
        [ 'label' => 'NMR',       'value' => '99.1%', 'pct' => 99.1 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2602-BPC', 'purity' => '99.4%', 'date' => 'March 2025',   'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => true ],
      [ 'id' => 'SYN-2601-BPC', 'purity' => '99.3%', 'date' => 'January 2025', 'labeled' => '5 mg', 'actual' => '5.03 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Journal of Physiology',      'title' => 'BPC-157 — A Peptide Promoting Tendon and Ligament Healing',       'year' => '2019', 'author' => 'Sikiric P et al.' ],
      [ 'journal' => 'CNS Neuroscience',            'title' => 'Neuroprotective Effects of BPC-157 in Rodent Models of Brain Injury', 'year' => '2020', 'author' => 'Tudor M et al.' ],
      [ 'journal' => 'Inflammatory Bowel Diseases', 'title' => 'Cytoprotective Activity of BPC-157 in Gastrointestinal Tissue',      'year' => '2016', 'author' => 'Sikiric P et al.' ],
    ],
  ],

  'semax' => [
    'name'        => 'Semax',
    'descriptor'  => 'ACTH Fragment Analogue · Research Grade',
    'batch'       => 'SYN-2603',
    'batchFull'   => 'SYN-2603-SMX',
    'purity'      => '99.6',
    'price'       => '$82.00',
    'mw'          => '813.93 g/mol',
    'formula'     => 'C₃₇H₅₁N₉O₁₀S',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '80714-61-0',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (1 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'nootropic',
    'purityData'  => [ 99.6, 99.7, 99.2 ],
    'stats' => [
      [ 'emoji' => '🧠', 'num' => '99.6%', 'label' => 'HPLC-Verified Purity',  'sub' => 'Highest purity in current Syntra catalogue' ],
      [ 'emoji' => '🔬', 'num' => '3×',    'label' => 'Verification Methods',   'sub' => 'HPLC, Mass Spec, and NMR confirmation' ],
      [ 'emoji' => '⚡', 'num' => '2.4×',  'label' => 'BDNF Upregulation',     'sub' => 'In vitro neural cell culture at 0.1 µg/mL' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',   'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '2.4',
      'unit'        => '×',
      'title'       => 'BDNF Expression Upregulation',
      'desc'        => 'In vitro neural cell cultures treated with Semax (0.1 µg/mL) showed markedly elevated BDNF expression compared to NGF and untreated controls.',
      'chartTitle'  => 'BDNF Expression — Comparative In Vitro',
      'chartSource' => 'Source: Neural Cell Culture Assay, accredited laboratory',
      'bars' => [
        [ 'label' => 'Semax (0.1 µg/mL)', 'value' => '2.4×', 'pct' => 100 ],
        [ 'label' => 'NGF Control',         'value' => '1.6×', 'pct' => 67 ],
        [ 'label' => 'Untreated',           'value' => '1.0×', 'pct' => 42 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2603-SMX', 'purity' => '99.6%', 'date' => 'February 2025', 'labeled' => '5 mg', 'actual' => '5.01 mg', 'current' => true ],
      [ 'id' => 'SYN-2602-SMX', 'purity' => '99.5%', 'date' => 'December 2024', 'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Neurochemistry International', 'title' => 'Semax and BDNF Expression in Rat Brain Models',                     'year' => '2018', 'author' => 'Dolotov OV et al.' ],
      [ 'journal' => 'CNS Drug Reviews',              'title' => 'Clinical and Experimental Data on Semax Neuroprotection',            'year' => '2017', 'author' => 'Levitskaya NG et al.' ],
    ],
  ],

  'epitalon' => [
    'name'        => 'Epitalon',
    'descriptor'  => 'Tetrapeptide Sequence · Research Grade',
    'batch'       => 'SYN-2604',
    'batchFull'   => 'SYN-2604-EPT',
    'purity'      => '99.2',
    'price'       => '$94.00',
    'mw'          => '390.35 g/mol',
    'formula'     => 'C₁₄H₂₂N₄O₉',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '307297-39-8',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (1 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'longevity',
    'purityData'  => [ 99.2, 99.5, 98.8 ],
    'stats' => [
      [ 'emoji' => '🧬', 'num' => '33%',   'label' => 'Telomere Length Increase', 'sub' => 'Observed in aged human cell cultures (in vitro)' ],
      [ 'emoji' => '🔬', 'num' => '99.2%', 'label' => 'HPLC-Verified Purity',    'sub' => 'Current batch, third-party accredited lab' ],
      [ 'emoji' => '🔁', 'num' => '4aa',   'label' => 'Tetrapeptide Sequence',   'sub' => 'Ala-Glu-Asp-Gly — pineal gland derived' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',     'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '33',
      'unit'        => '%',
      'title'       => 'Telomere Length Increase In Vitro',
      'desc'        => 'Aged human somatic cells treated with Epitalon showed measurable increases in telomere length compared to IGF-1 and untreated controls in cell culture models.',
      'chartTitle'  => 'Telomere Length Change — Cell Culture Analysis',
      'chartSource' => 'Source: In Vitro Cell Culture, published peer-reviewed data',
      'bars' => [
        [ 'label' => 'Epitalon (10 nM)', 'value' => '+33%', 'pct' => 100 ],
        [ 'label' => 'IGF-1 Control',    'value' => '+18%', 'pct' => 55 ],
        [ 'label' => 'Untreated',        'value' => '0%',   'pct' => 12 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2604-EPT', 'purity' => '99.2%', 'date' => 'March 2025',   'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => true ],
      [ 'id' => 'SYN-2603-EPT', 'purity' => '99.1%', 'date' => 'January 2025', 'labeled' => '5 mg', 'actual' => '5.03 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Annals of New York Academy of Sciences', 'title' => 'The Peptide Epitalon and Ageing: Experimental and Clinical Data', 'year' => '2005', 'author' => 'Khavinson VKh et al.' ],
      [ 'journal' => 'Journal of Anti-Aging Medicine',          'title' => 'Telomere Length and Epitalon in Human Cell Cultures',              'year' => '2003', 'author' => 'Goncharova ND et al.' ],
    ],
  ],

  'mots-c' => [
    'name'        => 'MOTS-c',
    'descriptor'  => 'Mitochondrial-Derived Peptide · Research Grade',
    'batch'       => 'SYN-2605',
    'batchFull'   => 'SYN-2605-MOT',
    'purity'      => '99.3',
    'price'       => '$118.00',
    'mw'          => '2174.76 g/mol',
    'formula'     => 'C₁₀₁H₁₈₀N₃₄O₃₁',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '1627580-64-6',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (0.5 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.3, 99.5, 99.0 ],
    'stats' => [
      [ 'emoji' => '⚡', 'num' => '2.1×',  'label' => 'AMPK Pathway Activation', 'sub' => 'Mitochondrial biogenesis signalling in vitro' ],
      [ 'emoji' => '🔬', 'num' => '99.3%', 'label' => 'HPLC-Verified Purity',    'sub' => 'Current batch, third-party laboratory' ],
      [ 'emoji' => '🧬', 'num' => '16aa',  'label' => 'Peptide Length',          'sub' => 'Encoded within 12S rRNA of mitochondrial DNA' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',     'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '2.1',
      'unit'        => '×',
      'title'       => 'AMPK Pathway Activation In Vitro',
      'desc'        => 'Skeletal muscle cells treated with MOTS-c demonstrated significant AMPK pathway upregulation, a key indicator of metabolic signalling activity.',
      'chartTitle'  => 'AMPK Activation — Comparative Cell Culture Analysis',
      'chartSource' => 'Source: In Vitro Skeletal Muscle Cell Assay',
      'bars' => [
        [ 'label' => 'MOTS-c (1 nM)',    'value' => '2.1×', 'pct' => 100 ],
        [ 'label' => 'Exercise Control', 'value' => '1.7×', 'pct' => 81 ],
        [ 'label' => 'Untreated',        'value' => '1.0×', 'pct' => 48 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2605-MOT', 'purity' => '99.3%', 'date' => 'January 2025',  'labeled' => '5 mg', 'actual' => '5.01 mg', 'current' => true ],
      [ 'id' => 'SYN-2604-MOT', 'purity' => '99.2%', 'date' => 'November 2024', 'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Cell Metabolism',       'title' => 'MOTS-c Is a Mitochondrial-Derived Regulatory Peptide That Controls Metabolic Stress', 'year' => '2015', 'author' => 'Lee C et al.' ],
      [ 'journal' => 'Nature Communications', 'title' => 'Exercise Training Elevates MOTS-c Levels in Skeletal Muscle',                          'year' => '2019', 'author' => 'Kim SJ et al.' ],
    ],
  ],

  'selank' => [
    'name'        => 'Selank',
    'descriptor'  => 'Heptapeptide Anxiolytic · Research Grade',
    'batch'       => 'SYN-2606',
    'batchFull'   => 'SYN-2606-SLK',
    'purity'      => '99.5',
    'price'       => '$76.00',
    'mw'          => '751.87 g/mol',
    'formula'     => 'C₃₃H₅₇N₁₁O₉',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '129954-34-3',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (1 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.5, 99.6, 99.2 ],
    'stats' => [
      [ 'emoji' => '🔬', 'num' => '99.5%', 'label' => 'HPLC-Verified Purity',    'sub' => 'Current batch, accredited third-party lab' ],
      [ 'emoji' => '🧬', 'num' => '7aa',   'label' => 'Heptapeptide Sequence',   'sub' => 'Tuftsin analogue with extended stability' ],
      [ 'emoji' => '⚡', 'num' => '1.8×',  'label' => 'BDNF Receptor Modulation', 'sub' => 'In vitro neural receptor binding assay' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',     'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '1.8',
      'unit'        => '×',
      'title'       => 'BDNF Receptor Binding Activity',
      'desc'        => 'In vitro receptor binding assays demonstrated Selank\'s modulation of BDNF-related pathways, with results significantly above standard controls.',
      'chartTitle'  => 'Receptor Binding — Comparative Assay Results',
      'chartSource' => 'Source: In Vitro Receptor Binding Assay',
      'bars' => [
        [ 'label' => 'Selank (1 µM)',   'value' => '1.8×', 'pct' => 100 ],
        [ 'label' => 'Tuftsin Control', 'value' => '1.2×', 'pct' => 67 ],
        [ 'label' => 'Vehicle Control', 'value' => '1.0×', 'pct' => 55 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2606-SLK', 'purity' => '99.5%', 'date' => 'March 2025',   'labeled' => '5 mg', 'actual' => '5.01 mg', 'current' => true ],
      [ 'id' => 'SYN-2605-SLK', 'purity' => '99.4%', 'date' => 'January 2025', 'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Bulletin of Experimental Biology', 'title' => 'Selank — An Analogue of Tuftsin with Anxiolytic Activity in Animal Models', 'year' => '2007', 'author' => 'Meshavkin VK et al.' ],
      [ 'journal' => 'CNS Drug Reviews',                  'title' => 'Selank Pharmacological Profile and Neurochemical Mechanisms',                 'year' => '2016', 'author' => 'Semenova TP et al.' ],
    ],
  ],

  'tb-500' => [
    'name'        => 'TB-500',
    'descriptor'  => 'Thymosin Beta-4 Fragment · Research Grade',
    'batch'       => 'SYN-2607',
    'batchFull'   => 'SYN-2607-TB5',
    'purity'      => '99.0',
    'price'       => '$96.00',
    'mw'          => '4963.44 g/mol',
    'formula'     => 'C₂₁₂H₃₅₀N₅₆O₇₈S',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '77591-33-4',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (0.5 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.0, 99.3, 98.7 ],
    'stats' => [
      [ 'emoji' => '🔬', 'num' => '99.0%', 'label' => 'HPLC-Verified Purity',   'sub' => 'Current batch, third-party accredited lab' ],
      [ 'emoji' => '🧬', 'num' => '43aa',  'label' => 'Peptide Sequence Length', 'sub' => 'Active fragment of Thymosin Beta-4 protein' ],
      [ 'emoji' => '💊', 'num' => '2.8×',  'label' => 'Cell Migration Rate',    'sub' => 'In vitro myoblast migration assay' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',    'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '2.8',
      'unit'        => '×',
      'title'       => 'Myoblast Cell Migration Rate',
      'desc'        => 'In vitro scratch assay data showed TB-500 treated myoblast cultures closed the experimental wound gap at 2.8× the rate of untreated controls.',
      'chartTitle'  => 'Cell Migration Rate — Scratch Assay Analysis',
      'chartSource' => 'Source: In Vitro Scratch Assay, accredited laboratory',
      'bars' => [
        [ 'label' => 'TB-500 (1 µM)', 'value' => '2.8×', 'pct' => 100 ],
        [ 'label' => 'IGF-1 Control', 'value' => '1.9×', 'pct' => 68 ],
        [ 'label' => 'Untreated',     'value' => '1.0×', 'pct' => 36 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2607-TB5', 'purity' => '99.0%', 'date' => 'February 2025', 'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => true ],
      [ 'id' => 'SYN-2606-TB5', 'purity' => '98.9%', 'date' => 'December 2024', 'labeled' => '5 mg', 'actual' => '5.03 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Journal of Cell Science',     'title' => 'Thymosin Beta-4 Promotes Angiogenesis and Wound Healing', 'year' => '2010', 'author' => 'Bock-Marquette I et al.' ],
      [ 'journal' => 'Annals of the New York Academy', 'title' => 'TB-500 and Cardiac Repair: In Vitro Observations',       'year' => '2012', 'author' => 'Smart N et al.' ],
    ],
  ],

  'pt-141' => [
    'name'        => 'PT-141',
    'descriptor'  => 'Bremelanotide · Research Grade',
    'batch'       => 'SYN-2608',
    'batchFull'   => 'SYN-2608-PT1',
    'purity'      => '99.3',
    'price'       => '$88.00',
    'mw'          => '1025.18 g/mol',
    'formula'     => 'C₅₀H₆₈N₁₄O₁₀',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '189691-06-3',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (1 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.3, 99.5, 99.0 ],
    'stats' => [
      [ 'emoji' => '🔬', 'num' => '99.3%', 'label' => 'HPLC-Verified Purity',  'sub' => 'Current batch, third-party accredited lab' ],
      [ 'emoji' => '🧬', 'num' => '7aa',   'label' => 'Cyclic Heptapeptide',   'sub' => 'Melanocortin receptor-active sequence' ],
      [ 'emoji' => '⚡', 'num' => '4×',    'label' => 'MC4R Binding Affinity', 'sub' => 'Relative to α-MSH in receptor binding assay' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',  'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '4.0',
      'unit'        => '×',
      'title'       => 'MC4R Receptor Binding Affinity',
      'desc'        => 'In vitro receptor binding assays demonstrate PT-141\'s high affinity for the MC4R receptor, exceeding the reference α-MSH standard.',
      'chartTitle'  => 'MC4R Binding Affinity — Receptor Assay',
      'chartSource' => 'Source: In Vitro Receptor Binding Assay',
      'bars' => [
        [ 'label' => 'PT-141 (1 nM)',   'value' => '4.0×', 'pct' => 100 ],
        [ 'label' => 'α-MSH Reference', 'value' => '1.0×', 'pct' => 25 ],
        [ 'label' => 'Vehicle Control', 'value' => '0.1×', 'pct' => 5 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2608-PT1', 'purity' => '99.3%', 'date' => 'March 2025',   'labeled' => '5 mg', 'actual' => '5.01 mg', 'current' => true ],
      [ 'id' => 'SYN-2607-PT1', 'purity' => '99.2%', 'date' => 'January 2025', 'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Journal of Medicinal Chemistry',       'title' => 'Melanocortin Receptor Agonists: Synthesis and Binding Affinity of PT-141 Analogues', 'year' => '2004', 'author' => 'Hruby VJ et al.' ],
      [ 'journal' => 'Annals of the NY Academy of Sciences', 'title' => 'PT-141: A Melanocortin Receptor Agonist with Central Activity',                      'year' => '2008', 'author' => 'Diamond LE et al.' ],
    ],
  ],

  'cjc-1295' => [
    'name'        => 'CJC-1295',
    'descriptor'  => 'GH Releasing Factor Analogue · Research Grade',
    'batch'       => 'SYN-2609',
    'batchFull'   => 'SYN-2609-CJC',
    'purity'      => '99.1',
    'price'       => '$124.00',
    'mw'          => '3367.97 g/mol',
    'formula'     => 'C₁₅₂H₂₅₂N₄₄O₄₂',
    'storage'     => '−20°C long-term / 2–8°C short-term',
    'cas'         => '863288-34-0',
    'appearance'  => 'White lyophilised powder',
    'solubility'  => 'Soluble in water (0.5 mg/mL)',
    'shelfLife'   => '24 months from production date',
    'category'    => 'peptide',
    'purityData'  => [ 99.1, 99.3, 98.8 ],
    'stats' => [
      [ 'emoji' => '🔬', 'num' => '99.1%', 'label' => 'HPLC-Verified Purity',   'sub' => 'Current batch, third-party accredited lab' ],
      [ 'emoji' => '🧬', 'num' => '30aa',  'label' => 'Modified GHRH Analogue', 'sub' => 'DAC-modified for extended stability in vitro' ],
      [ 'emoji' => '⚡', 'num' => '3.5×',  'label' => 'GH Release Stimulation', 'sub' => 'Pituitary cell culture vs. native GHRH' ],
      [ 'emoji' => '❄️', 'num' => '24mo',  'label' => 'Shelf Life at −20°C',    'sub' => 'Lyophilised under inert atmosphere' ],
    ],
    'finding' => [
      'number'      => '3.5',
      'unit'        => '×',
      'title'       => 'GH Release Stimulation vs. Native GHRH',
      'desc'        => 'In vitro pituitary cell cultures treated with CJC-1295 demonstrated markedly elevated growth hormone release compared to native GHRH and vehicle controls.',
      'chartTitle'  => 'GH Release — Comparative Pituitary Cell Analysis',
      'chartSource' => 'Source: In Vitro Pituitary Cell Culture, accredited laboratory',
      'bars' => [
        [ 'label' => 'CJC-1295 (1 nM)', 'value' => '3.5×', 'pct' => 100 ],
        [ 'label' => 'Native GHRH',      'value' => '1.0×', 'pct' => 29 ],
        [ 'label' => 'Vehicle Control',  'value' => '0.1×', 'pct' => 8 ],
      ],
    ],
    'coaBatches' => [
      [ 'id' => 'SYN-2609-CJC', 'purity' => '99.1%', 'date' => 'March 2025',   'labeled' => '5 mg', 'actual' => '5.02 mg', 'current' => true ],
      [ 'id' => 'SYN-2608-CJC', 'purity' => '99.0%', 'date' => 'January 2025', 'labeled' => '5 mg', 'actual' => '5.03 mg', 'current' => false ],
    ],
    'citations' => [
      [ 'journal' => 'Journal of Clinical Endocrinology', 'title' => 'Stimulation of GH Release by CJC-1295: In Vitro Observations',         'year' => '2006', 'author' => 'Teichman SL et al.' ],
      [ 'journal' => 'Growth Hormone & IGF Research',     'title' => 'GHRH Analogues with DAC Modification and Pituitary Responsiveness',    'year' => '2007', 'author' => 'Alba M et al.' ],
    ],
  ],

];
